### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Swythabeast** [BigBoiCJ/SteamAutoCracker#30]
Hello, I'am new to using this program (and sorry for my bad english).
I answer correctly to the program (locations, questions about steamless...) and I have this error: 
Traceback (most recent call last):
  File "steam_auto_cracker.py", line 481, in <module>
PermissionError: [WinError 5] Access is denied: 'E:/Pirate/Tourist Bus Simulator\\Engine\\Binaries\\ThirdParty\\Steamworks\\Steamv139\\Win64/steam_api64.dll'

I try to elevate the program but nothing change.. Can you help me please?

**Comment by Swythabeast** [comment]
Finally I just correct that with uncheck read-only on steam_api64.dll file but I think I can't crack the game because he say me : Unable to load library steamclient64.dll.. Can you confirm that?

**Comment by BigBoiCJ** [comment]
I was going to say it's probably because you enabled read-only, so good you found out :)

> Unable to load library steamclient64.dll

I believe that's because the game you're trying to crack uses another type of DRM where it will check if the Steam client is running and will try to contact it instead of using the other regular methods. This is less common but still happens. Sadly, SAC can't bypass this type of DRM.

You can try searching for Goldberg's emu which can bypass this, but you'll have to set it up manually. Else, you can try searching for an existing crack on the CS.RIN.RU forum :)

**Comment by BigBoiCJ** [comment]
Feel free to re-open this issue or to create a new one if you need to :)
